const languageMap = {
  'basicInfo':"Basic Info",
  'name': 'name',
  'email': 'Email',
  'title': 'Thesis Title',
  'wordLimit': 'Word Limit',
  'deadline': 'Deadline',
  'language': 'Language',
  'require': "Requesments",
  'noOrder': "No Order",
  'paper': "Thesis",
  'handIn': 'have in hand',
  'finish': 'finish',
  'login': 'regeister/login',
  'english': "English",
  'spanish': "Spanish",
  'submit': 'submit',
  'upload': 'upload file(Allow multiple uploads)',
  'mine': 'Mine',
  'newOrder': 'New Order',
  'status': 'Status',
  'orderStatus': 'Order Status',

  'orderComp': "Order Complete",
  'startpoli': 'Start polishing',
  '2000words': '2000 words completed',
  '1000words': '1000 words completed',
  'orderSart': 'Order Start',

  'registerTips': "Registration is required before use",
  'loginTips': 'Login successful',
  'registerOk': 'Register Ok',
  'submitSuc': "Submit Success",

  'fileLimit': 'File size cannot exceed 2MB!',
  'fileTypeLimit': 'Format must be PDF or word!',

  'fileLimit': 'The file size cannot exceed 4MB!🥺',
  'fileTypeLimit': 'Format must be PDF or word！🥺',
  'languageLimit':'language required🥺🥺',
  'nameLimit': 'Name required🥺🥺',
  'titleLimit': 'Title required🥺🥺',
  'emailLimit':'Email required🥺',
  'emailFormLimit':'Please fill in the correct email format🥺',
  'wordLimitReq':'Word limit required🥺',
  'wordLimitNum': "The word limit must be a number 🥺",
  'dateLimit':'Deadline is too close. Please give us more time🥺',
  'requireLimit':'Basic requirement is required🥺',
  'uploadFileTips': 'The file size should be less than 2MB. If the upload fails, please contact customer service directly'
}

export default languageMap;