const languageMap = {
  'basicInfo':"Basic Info",
  'name': 'name',
  'email': 'Email',
  'title': 'Thesis Title',
  'wordLimit': 'Word Limit',
  'deadline': 'Deadline',
  'language': 'Language',
  'require': "Requesments",
  'noOrder': "Order List is Empty",
  'paper': "Thesis",
  'handIn': 'Pending..',
  'finish': 'Done',
  'login': 'Regeister/Login',
  'english': "English",
  'spanish': "Spanish",
  'submit': 'Submit',
  'upload': 'Upload File(Allow Multiple Uploads)',
  'mine': 'Mine',
  'newOrder': 'New Order',
  'status': 'Status',
  'orderStatus': 'Order Status',

  'orderComp': "Order Complete",
  'startpoli': 'Start polishing',
  '2000words': '2000 Words Completed',
  '1000words': '1000 Words Completed',
  'orderSart': 'Order Created',

  'registerTips': "Registration is Required Before Use",
  'loginTips': 'Login Successful',
  'registerOk': 'Register Ok',
  'submitSuc': "Submit Success",

  'fileLimit': 'File size cannot exceed 2MB!',
  'fileTypeLimit': 'Format must be PDF or word!',

  'nameNote': 'Input your name',
  'emailNote': 'Input your email',
  'titleNote': 'Input your title',
  'wordLimitNote': 'Input your word Limit',
  'reqtNote': 'Input your requirements',

  'fileLimit': 'The file size cannot exceed 4MB!🥺',
  'fileTypeLimit': 'Format must be PDF or word！🥺',
  'languageLimit':'language required🥺🥺',
  'nameLimit': 'Name required🥺🥺',
  'titleLimit': 'Title required🥺🥺',
  'emailLimit':'Email required🥺',
  'emailFormLimit':'Please fill in the correct email format🥺',
  'wordLimitReq':'Word limit required🥺',
  'wordLimitNum': "The word limit must be a number 🥺",
  'dateLimit':'Deadline is too close. Please give us more time🥺',
  'requireLimit':'Basic requirement is required🥺',
  'uploadFileTips': 'The file size should be less than 2MB. If the upload fails, please contact customer service directly（Only local wechat upload is allowed）',
  'motto': 'Thanks for Trusting Nailed it 😆'
}

export default languageMap;
