const languageMap = {
  'basicInfo':"基本信息",
  'name': '姓名',
  'email': '邮箱',
  'title': '论文标题',
  'wordLimit': '字数限制',
  'deadline': '交稿期限',
  'language': '语言',
  'require': "具体需求",
  'noOrder': "暂无订单",
  'paper': "论文",
  'handIn': '进行中',
  'finish': '已完成',
  'login': '登录/注册',
  'english': "英语",
  'spanish': "西班牙语",
  'submit': '提交',
  'upload': '上传文件(允许多次上传)',
  'mine': '我的',
  'newOrder': '新建订单',
  'status': '状态',
  'orderStatus': "订单状态",

  'orderComp': "订单完成",
  'startpoli': '开始润色',
  '2000words': '已完成2000字',
  '1000words': '已完成1000字',
  'orderSart': '开始接单',

  'registerTips': "使用过前需要注册",
  'loginTips': '登录成功',

  'fileLimit': '文件大小不能超过4MB!🥺',
  'fileTypeLimit': '格式必须为pdf或者word！🥺',
  'languageLimit':'语言为必选项🥺',
  'nameLimit': '姓名为必选项🥺',
  'titleLimit': '标题为必选项🥺',
  'emailLimit':'Email为必选项🥺',
  'emailFormLimit':'请填写正确Email格式🥺',
  'wordLimitReq':'字数限制必填🥺',
  'dateLimit':'Deadline也太近啦😣请多给我们一些时间🥺',
  'requireLimit':'基本需求必填🥺',
}

export default languageMap;